index.js
i have html encoded userName before displaying it which fixes the issue https://github.com/arpitghura/typing-test/issues/3
=> encoded userName to prevent from XSS

index.css, index.html
Fixed the footer CSS and added Copyrights mark. Finally with a background it's looking good.
=> Centered the footer, added a gradient background for the footer. Changes made in index.css and index.html

index.js, practice.css
Reverts arpitghura/typing-test#15
=> Revert "Now user won't be able to copy the quote and paste into the usetInput."

index.css, index.html
Modified the navbar as discussed in issue #14.
Please let me know if any changes are to be made.
=> fix: add GitHub icon and link

README.md
Hey @arpitghura 
This is the final commit from my side, give your input also if there is a need for more changes to the readme.md file.
Regards.
Harsh
=> Final Readme.md file

practice.css
Not able to fix the heading and button while we scroll horizontally. Could you help me with this?
=> table fixed

practice.css, practice.html
- Add navbar and footer with the same styling as the homepage.
=> Add navbar and footer to practice page

practice.css
Changed the practice.css file
reduced the space under the div NameModal
so that there is no extra space left around
=> changed the practice.css

about.html, assets/css/index.css, assets/js/index.js, assets/js/practice.js, assets/js/profile.js, index.html, practice.html, profile.html
Added mobile nav-bar for responsiveness if site is visited from mobile app
Kindly review and give me feedback
=> added mobile nav-bar

about.html, assets/css/index.css
=> about page aligned

about.html, assets/css/dark.css, assets/css/index.css, assets/css/practice.css, assets/js/dark.js, practice.html, profile.html
Lemme know if anything need to changed.
=> Added Dark Mode

about.html, assets/css/index.css, assets/js/dark.js, index.html, practice.html, profile.html, testimonials.html
@arpitghura hey i have solved this issue #77
i added `<i id="icon1" onclick="change('icon1')" onclick="toggleLightDarkMode()" class="bx bx-moon dark-btn" style="font-size: x-large;"></i>`  in practice.html.
similarly, I added `<i id="icon1" onclick="change('icon1')" onclick="toggleLightDarkMode()" class="bx bx-moon dark-btn" style="font-size: x-large;"></i>` to about and profile page also.
Then i added js to change the icon from moon to sun using 
`function change (iconID){
if(document.getElementById(iconID).className=="bx bx-moon dark-btn"){
document.getElementById(iconID).className = "bx bx-sun dark-btn";
}
else{
document.getElementById(iconID).className = "bx bx-moon dark-btn";
}
}
`
and called it whenever needed.
here is a video attached to show that its working: …
=> replaced dark mod button text with icon.

assets/css/index.css, index.html
I have fixed the footer bug metioned above in index.css and is reflected across all the pages.
=> fixed footer bug

about.html, assets/css/about.css
fixes: #98 
[screen-recording (3).webm](https://user-images.githubusercontent.com/91966855/216388356-4183798c-054c-44a0-aa96-37e28c88c030.webm)
Note : i am contributing in Diversion2k23
=> changed ui of about section

about.html, assets/css/index.css, index.html, practice.html, profile.html, testimonials.html
=> added icons in the navbar

about.html, assets/css/index.css, assets/css/practice.css, assets/css/profile.css, assets/css/testimonials.css, assets/js/dark.js, assets/js/index.js, assets/js/practice.mjs, assets/js/profile.js, assets/js/sentence.mjs, index.html, practice.html, profile.html, testimonials.html
To make the code easier for other developers to comprehend, I have provided brief descriptions of the code snippets in the HTML, CSS, and Javascript files.
This pull request solves #91 .
**Code Snippets:**
=> Documentation of Source Code

assets/css/index.css
color and the width of the scroll bar is not correct ,i'm correcting that
=> Change in Colors and width of scroll bar

assets/css/profile.css
Changed the data history background, 
changed reset data button
changed margin design 
increase font size and height of each row.
=> Update the profile section #117 solve

README.md
* Update the Year of the participation in KWOC from 2022 to 2023.
* Created DIVERSION 2023 & IWOC 2023 badges.
* Created DISCORD badge by the provided link.
**I am participating under DIVERSION 2023.**
=> [FIX] Add Badges in README file #103

assets/css/profile.css, assets/js/profile.js, profile.html
managed data of typing and added a delete button to delete the user name
features added
1-delete button provided to delete userName
2-now the user can delete the history of typing data without changing userName(_means no need to provide username again and again after deleting user typing history).
Note--if the user wants to delete all data then the user has to click on the button reset and delete
fixed--
video--
you can skip video from 0.31 to 1:43 (this time taken to pass the game)
https://user-images.githubusercontent.com/94105514/220374784-475cb16b-03a7-4063-be93-46ecf2d1bed0.mp4
=> managed data of typing and added delete btn to delete user name

assets/css/practice.css, assets/js/practice.mjs, practice.html
Issue number: #134 
To check the position of the user input text box, I have set a condition of comparing dynamic text box height with 80% of the viewport height. Firstly I have created two text boxes in practice.html, and commented out the previous one. 
Then, I styled them in practice.css. And at last, I added some elements in practice.mjs, and with the condition check I assigned the element to the variable declared in that file.
Hope it helped!
=> [Fixes: #134] Placing textbox on screen
